apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeweb-deployment
  labels:
    app: cafeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeapp
  template:
    metadata:
      labels:
        app: cafeapp 
    spec:
      containers:
      - name: cafeserver
        image: muhammadshoaib100/cafe-app:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: cafeapp-service
spec:
  selector:
    app: cafeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
